### ISSUE TITLE
Chybný odkaz

### ISSUE THREAD

**Issue by pesikj** [Czechitas-Python/uvod-do-progr-1#28]
Odkaz je na této stránce:
https://kodim.cz/kurzy/uvod-do-progr-1/priprava/jazyky-nastroje/instalace-python

Má vést sem: 
https://kodim.cz/kurzy/uvod-do-progr-1/priprava/jazyky-nastroje/overeni

![image](https://user-images.githubusercontent.com/15179154/185940032-e7318bfe-10bc-494e-9297-1098f2f559ce.png)

**Comment by lutydlitatova** [comment]
@pesikj Kam tě to teď hází? Funguje mi to správně...

**Comment by pesikj** [comment]
@lutydlitatova Házelo to error 404, teď už je to OK.

**Comment by lutydlitatova** [comment]
Super, díky 🙂

**Comment by pesikj** [comment]
@lutydlitatova Prosím tě, tak ta chyba tam pořád je, akorát se projevuje na stránce: https://kodim.cz/kurzy/uvod-do-progr-1/priprava/jazyky-nastroje

**Comment by pesikj** [comment]
@lutydlitatova Když klikneš zde https://kodim.cz/kurzy/uvod-do-progr-1 na Jazyky a nástroje, tak ten odkaz nefunguje.

Když klikneš zde https://kodim.cz/kurzy/uvod-do-progr-1 na Jazyky a nástroje a pak v panelu vlevo klineš na Instalace jazyka Python, tak ti to vloží do adresy */instalace-python** a pak to funguje. Asi nějaký problém s relativním odkazem. Ale je to záludný bug. :-D

**Comment by lutydlitatova** [comment]
Už to vidím 🙂

**Comment by pavelsuk** [comment]
Ten odkaz je tam 2x - jeste u linuxu. Dival jsem se na to, ale moc nevim, jak to opravit. Pokud tam chceme relativni cestu, ale pritom se na tu stranku da dostat pres 2 ruzna URLka, tak to bude zlobit z jednoho nebo druheho pohledu. Tedy pokud neni jeste nejaky specialni zpusob, jak v kodim.cz zapsat link na sibling item, nebo prinutit kodim.cz, aby se i u prvniho itemu to slo na jeho full url. Nejaky dalsi napad?

**Comment by podlomar** [comment]
Opraveno ve verzi 1.5.7

**Comment by pavelsuk** [comment]
Jo, funguje to. Zaviram.
