### ISSUE TITLE
Část sekvence řešit ve skriptu

### ISSUE THREAD

**Issue by pesikj** [Czechitas-Python/uvod-do-progr-1#38]
Je třeba upravit příklad na první stránce a zadání příkladu 1.

**Comment by lutydlitatova** [comment]
@pesikj , Myslíš tyhle dvě části (a ten příklad)?
* https://kodim.cz/kurzy/uvod-do-progr-1/prvni-krucky/sekvence/retezce
* https://kodim.cz/kurzy/uvod-do-progr-1/prvni-krucky/sekvence/seznamy
