### ISSUE TITLE
Příklady u lekce Vstup a výstup

### ISSUE THREAD

**Issue by pesikj** [Czechitas-Python/uvod-do-progr-1#43]
Upravit příklady tak, aby přetypování mělo praktický význam

**Comment by ZelenyMartin** [comment]
Podle mě už je to vyřešeno v https://github.com/Czechitas-Python/uvod-do-progr-1/commit/830574c736dec05cb2437e4f64ee0b880ef2e1a3

Nebo je ještě něco mezi příklady, co nedává smysl?
https://kodim.cz/programovani/uvod-do-progr-1/prvni-krucky/vstup-vystup/excs

**Comment by pesikj** [comment]
Ano, můžeme to zavřít.
