### ISSUE TITLE
Zbavit se práce v interpreteru

### ISSUE THREAD

**Issue by lutydlitatova** [Czechitas-Python/uvod-do-progr-1#46]
Je potřeba přepsat kapitoly

- [x] Čísla a řetězce
- [x] Proměnné
- [x] Funkce a moduly

tak, aby se od začátku pracovalo s programy, nikoliv v interpreteru. 

Jak pracovat s interpreterem se může přesunout do Čtení na doma.

**Comment by ZelenyMartin** [comment]
Resolved by #57
