### ISSUE TITLE
Chybí kus kódu v příkladech na Cykly

### ISSUE THREAD

**Issue by AnetaPopelova** [Czechitas-Python/uvod-do-progr-1#47]
https://kodim.cz/kurzy/uvod-do-progr-1/prvni-krucky/cykly/cyklus-for

V posledním ukázkovém kódu ve výkladu kapitoly Cykly chybí seznam `cisla`, se kterým se následně pracuje. 

```
soucet = 0
for cislo in cisla:
    soucet = soucet + cislo
```

**Comment by pavelsuk** [comment]
Viz merge request #48

**Comment by pavelsuk** [comment]
nebo jednodussi verze v #49

**Comment by lutydlitatova** [comment]
Fixed by #49
