### ISSUE TITLE
Spojeni stranek Hodnoty a Aritmetické operátory

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/uvod-do-progr-1#59]
V prvni kapitole Čísla a řetězce navrhuji spojit stranky [Hodnoty](https://kodim.cz/kurzy/uvod-do-progr-1/prvni-krucky/cisla-retezce/hodnoty) a [Aritmetické operátory](https://kodim.cz/kurzy/uvod-do-progr-1/prvni-krucky/cisla-retezce/aritmeticke-operatory) na jednu stranu. Stranka Hodnoty je moc kratka na sama o sobe nevypovidajici.

**Comment by ZelenyMartin** [comment]
Prosím o souhlas @pesikj, jestli to mam realizovat.

**Comment by pesikj** [comment]
Souhlasím.
