### ISSUE TITLE
Prohozeni cviceni v kap. Proměnné

### ISSUE THREAD

**Issue by ZelenyMartin** [Czechitas-Python/uvod-do-progr-1#61]
V kapitole Proměnné navrhuji prohodit ty novejsi [Úlohy na doma](https://kodim.cz/kurzy/uvod-do-progr-1/prvni-krucky/promenne/extra-excs), aby se delaly na lekci a ty starsi ze stranky [Cvičení](https://kodim.cz/kurzy/uvod-do-progr-1/prvni-krucky/promenne/excs) by byly na doma.

Smazat _Tip: Jednotlivé výpočty nemusíte kopírovat ani psát znovu, v terminálu stačí použít šipku nahoru._ z [Plánování svatby](https://kodim.cz/kurzy/uvod-do-progr-1/prvni-krucky/promenne/extra-excs#extra-excs%3Eplanovani-svatby) (nedava smysl).

**Comment by ZelenyMartin** [comment]
Prosím o souhlas @pesikj, jestli to mam realizovat.

**Comment by pesikj** [comment]
Souhlasím.
